### ISSUE TITLE
Datashading of points seems to not work

### ISSUE THREAD

**Issue by GeoVizNow** [holoviz/holoviews#5741]
#### ALL software version info
holoviews: 1.16.1
panel: 1.0.2
pandas: 1.5.3
bokeh: 3.1.1
numba: 0.57.0
numpy: 1.24.3
cython: 0.29.35
jupyter: 1.0.0
IPython: 8.12.2
code env: jupyter
browser: Chrome
os: windows 10

#### Description of expected behavior and the observed behavior
Expect datashade of holoviews points to work, but it seems to fail, see traceback below. Interesting to see if this is only on own system or if this is a general issue. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
from holoviews.operation.datashader import datashade

hv.extension('bokeh')

p = hv.Points(([1,2,3,4,5,2], [2,2,3,3,1,1]))
p

datashade(p)
```

#### Stack traceback and/or browser JavaScript console output

WARNING:param.dynamic_operation: Callable raised "AttributeError("module 'numpy' has no attribute 'warnings'")".
Invoked as dynamic_operation(height=400, scale=1.0, width=400, x_range=None, y_range=None)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File C:\hv116\test\.venv_wc\lib\site-packages\IPython\core\formatters.py:974, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    971     method = get_real_method(obj, self.print_method)
    973     if method is not None:
--> 974         return method(include=include, exclude=exclude)
    975     return None
    976 else:

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\dimension.py:1290, in Dimensioned._repr_mimebundle_(self, include, exclude)
   1283 def _repr_mimebundle_(self, include=None, exclude=None):
   1284     """
   1285     Resolves the class hierarchy for the class rendering the
   1286     object using any display hooks registered on Store.display
   1287     hooks.  The output of all registered display_hooks is then
   1288     combined and returned.
   1289     """
-> 1290     return Store.render(self)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\options.py:1425, in Store.render(cls, obj)
   1423 data, metadata = {}, {}
   1424 for hook in hooks:
-> 1425     ret = hook(obj)
   1426     if ret is None:
   1427         continue

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\ipython\display_hooks.py:280, in pprint_display(obj)
    278 if not ip.display_formatter.formatters['text/plain'].pprint:
    279     return None
--> 280 return display(obj, raw_output=True)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\ipython\display_hooks.py:254, in display(obj, raw_output, **kwargs)
    252 elif isinstance(obj, (HoloMap, DynamicMap)):
    253     with option_state(obj):
--> 254         output = map_display(obj)
    255 elif isinstance(obj, Plot):
    256     output = render(obj)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\ipython\display_hooks.py:142, in display_hook.<locals>.wrapped(element)
    140 try:
    141     max_frames = OutputSettings.options['max_frames']
--> 142     mimebundle = fn(element, max_frames=max_frames)
    143     if mimebundle is None:
    144         return {}, {}

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\ipython\display_hooks.py:202, in map_display(vmap, max_frames)
    199     max_frame_warning(max_frames)
    200     return None
--> 202 return render(vmap)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\ipython\display_hooks.py:69, in render(obj, **kwargs)
     66 if renderer.fig == 'pdf':
     67     renderer = renderer.instance(fig='png')
---> 69 return renderer.components(obj, **kwargs)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\plotting\renderer.py:399, in Renderer.components(self, obj, fmt, comm, **kwargs)
    396 embed = (not (dynamic or streams or self.widget_mode == 'live') or config.embed)
    398 if embed or config.comms == 'default':
--> 399     return self._render_panel(plot, embed, comm)
    400 return self._render_ipywidget(plot)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\plotting\renderer.py:406, in Renderer._render_panel(self, plot, embed, comm)
    404 doc = Document()
    405 with config.set(embed=embed):
--> 406     model = plot.layout._render_model(doc, comm)
    407 if embed:
    408     return render_model(model, comm)

File C:\hv116\test\.venv_wc\lib\site-packages\panel\viewable.py:719, in Viewable._render_model(self, doc, comm)
    717 if comm is None:
    718     comm = state._comm_manager.get_server_comm()
--> 719 model = self.get_root(doc, comm)
    721 if self._design and self._design.theme.bokeh_theme:
    722     doc.theme = self._design.theme.bokeh_theme

File C:\hv116\test\.venv_wc\lib\site-packages\panel\layout\base.py:279, in Panel.get_root(self, doc, comm, preprocess)
    275 def get_root(
    276     self, doc: Optional[Document] = None, comm: Optional[Comm] = None,
    277     preprocess: bool = True
    278 ) -> Model:
--> 279     root = super().get_root(doc, comm, preprocess)
    280     # ALERT: Find a better way to handle this
    281     if hasattr(root, 'styles') and 'overflow-x' in root.styles:

File C:\hv116\test\.venv_wc\lib\site-packages\panel\viewable.py:641, in Renderable.get_root(self, doc, comm, preprocess)
    639 wrapper = self._design._wrapper(self)
    640 if wrapper is self:
--> 641     root = self._get_model(doc, comm=comm)
    642     if preprocess:
    643         self._preprocess(root)

File C:\hv116\test\.venv_wc\lib\site-packages\panel\layout\base.py:164, in Panel._get_model(self, doc, root, parent, comm)
    162 root = root or model
    163 self._models[root.ref['id']] = (model, parent)
--> 164 objects = self._get_objects(model, [], doc, root, comm)
    165 props = self._get_properties(doc)
    166 props[self._property_mapping['objects']] = objects

File C:\hv116\test\.venv_wc\lib\site-packages\panel\layout\base.py:149, in Panel._get_objects(self, model, old_objects, doc, root, comm)
    147 else:
    148     try:
--> 149         child = pane._get_model(doc, root, model, comm)
    150     except RerenderError:
    151         return self._get_objects(model, current_objects[:i], doc, root, comm)

File C:\hv116\test\.venv_wc\lib\site-packages\panel\pane\holoviews.py:373, in HoloViews._get_model(self, doc, root, parent, comm)
    371     plot = self.object
    372 else:
--> 373     plot = self._render(doc, comm, root)
    375 plot.pane = self
    376 backend = plot.renderer.backend

File C:\hv116\test\.venv_wc\lib\site-packages\panel\pane\holoviews.py:454, in HoloViews._render(self, doc, comm, root)
    451     if comm:
    452         kwargs['comm'] = comm
--> 454 return renderer.get_plot(self.object, **kwargs)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\plotting\bokeh\renderer.py:70, in BokehRenderer.get_plot(self_or_cls, obj, doc, renderer, **kwargs)
     63 @bothmethod
     64 def get_plot(self_or_cls, obj, doc=None, renderer=None, **kwargs):
     65     """
     66     Given a HoloViews Viewable return a corresponding plot instance.
     67     Allows supplying a document attach the plot to, useful when
     68     combining the bokeh model with another plot.
     69     """
---> 70     plot = super().get_plot(obj, doc, renderer, **kwargs)
     71     if plot.document is None:
     72         plot.document = Document() if self_or_cls.notebook_context else curdoc()

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\plotting\renderer.py:218, in Renderer.get_plot(self_or_cls, obj, doc, renderer, comm, **kwargs)
    215     raise SkipRendering(msg.format(dims=dims))
    217 # Initialize DynamicMaps with first data item
--> 218 initialize_dynamic(obj)
    220 if not renderer:
    221     renderer = self_or_cls

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\plotting\util.py:257, in initialize_dynamic(obj)
    255     continue
    256 if not len(dmap):
--> 257     dmap[dmap._initial_key()]

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\spaces.py:1213, in DynamicMap.__getitem__(self, key)
   1211 # Not a cross product and nothing cached so compute element.
   1212 if cache is not None: return cache
-> 1213 val = self._execute_callback(*tuple_key)
   1214 if data_slice:
   1215     val = self._dataslice(val, data_slice)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\spaces.py:980, in DynamicMap._execute_callback(self, *args)
    977     kwargs['_memoization_hash_'] = hash_items
    979 with dynamicmap_memoization(self.callback, self.streams):
--> 980     retval = self.callback(*args, **kwargs)
    981 return self._style(retval)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\spaces.py:580, in Callable.__call__(self, *args, **kwargs)
    577     args, kwargs = (), dict(pos_kwargs, **kwargs)
    579 try:
--> 580     ret = self.callable(*args, **kwargs)
    581 except KeyError:
    582     # KeyError is caught separately because it is used to signal
    583     # invalid keys on DynamicMap and should not warn
    584     raise

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\util\__init__.py:1032, in Dynamic._dynamic_operation.<locals>.dynamic_operation(*key, **kwargs)
   1030 def dynamic_operation(*key, **kwargs):
   1031     key, obj = resolve(key, kwargs)
-> 1032     return apply(obj, *key, **kwargs)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\util\__init__.py:1024, in Dynamic._dynamic_operation.<locals>.apply(element, *key, **kwargs)
   1022 def apply(element, *key, **kwargs):
   1023     kwargs = dict(util.resolve_dependent_kwargs(self.p.kwargs), **kwargs)
-> 1024     processed = self._process(element, key, kwargs)
   1025     if (self.p.link_dataset and isinstance(element, Dataset) and
   1026         isinstance(processed, Dataset) and processed._dataset is None):
   1027         processed._dataset = element.dataset

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\util\__init__.py:1006, in Dynamic._process(self, element, key, kwargs)
   1004 elif isinstance(self.p.operation, Operation):
   1005     kwargs = {k: v for k, v in kwargs.items() if k in self.p.operation.param}
-> 1006     return self.p.operation.process_element(element, key, **kwargs)
   1007 else:
   1008     return self.p.operation(element, **kwargs)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\operation.py:194, in Operation.process_element(self, element, key, **params)
    191 else:
    192     self.p = param.ParamOverrides(self, params,
    193                                   allow_extra_keywords=self._allow_extra_keywords)
--> 194 return self._apply(element, key)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\operation.py:141, in Operation._apply(self, element, key)
    139     if not in_method:
    140         element._in_method = True
--> 141 ret = self._process(element, key)
    142 if hasattr(element, '_in_method') and not in_method:
    143     element._in_method = in_method

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\operation\datashader.py:1422, in datashade._process(self, element, key)
   1421 def _process(self, element, key=None):
-> 1422     agg = rasterize._process(self, element, key)
   1423     shaded = shade._process(self, agg, key)
   1424     return shaded

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\operation\datashader.py:1401, in rasterize._process(self, element, key)
   1398     op = transform.instance(**{k:v for k,v in extended_kws.items()
   1399                                if k in transform.param})
   1400     op._precomputed = self._precomputed
-> 1401     element = element.map(op, predicate)
   1402     self._precomputed = op._precomputed
   1404 unused_params = list(all_supplied_kws - all_allowed_kws)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\data\__init__.py:199, in PipelineMeta.pipelined.<locals>.pipelined_fn(*args, **kwargs)
    196     inst._in_method = True
    198 try:
--> 199     result = method_fn(*args, **kwargs)
    200     if PipelineMeta.disable:
    201         return result

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\data\__init__.py:1207, in Dataset.map(self, *args, **kwargs)
   1205 @wraps(LabelledData.map)
   1206 def map(self, *args, **kwargs):
-> 1207     return super().map(*args, **kwargs)

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\dimension.py:700, in LabelledData.map(self, map_fn, specs, clone)
    698     return deep_mapped
    699 else:
--> 700     return map_fn(self) if applies else self

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\operation.py:214, in Operation.__call__(self, element, **kwargs)
    210         return element.clone([(k, self._apply(el, key=k))
    211                               for k, el in element.items()])
    212     elif ((self._per_element and isinstance(element, Element)) or
    213           (not self._per_element and isinstance(element, ViewableElement))):
--> 214         return self._apply(element)
    215 elif 'streams' not in kwargs:
    216     kwargs['streams'] = self.p.streams

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\core\operation.py:141, in Operation._apply(self, element, key)
    139     if not in_method:
    140         element._in_method = True
--> 141 ret = self._process(element, key)
    142 if hasattr(element, '_in_method') and not in_method:
    143     element._in_method = in_method

File C:\hv116\test\.venv_wc\lib\site-packages\holoviews\operation\datashader.py:349, in aggregate._process(self, element, key)
    344 with warnings.catch_warnings():
    345     warnings.filterwarnings(
    346         action='ignore', message='casting datetime64',
    347         category=FutureWarning
    348     )
--> 349     agg = getattr(cvs, glyph)(dfdata, x.name, y.name, agg_fn, **agg_kwargs)
    350 if 'x_axis' in agg.coords and 'y_axis' in agg.coords:
    351     agg = agg.rename({'x_axis': x, 'y_axis': y})

File C:\hv116\test\.venv_wc\lib\site-packages\datashader\core.py:219, in Canvas.points(self, source, x, y, agg, geometry)
    212         raise ValueError(
    213             "source must be an instance of spatialpandas.GeoDataFrame or \n"
    214             "spatialpandas.dask.DaskGeoDataFrame.\n"
    215             "  Received value of type {typ}".format(typ=type(source)))
    217     glyph = MultiPointGeometry(geometry)
--> 219 return bypixel(source, self, glyph, agg)

File C:\hv116\test\.venv_wc\lib\site-packages\datashader\core.py:1258, in bypixel(source, canvas, glyph, agg, antialias)
   1255 canvas.validate()
   1257 # All-NaN objects (e.g. chunks of arrays with no data) are valid in Datashader
-> 1258 with np.warnings.catch_warnings():
   1259     np.warnings.filterwarnings('ignore', r'All-NaN (slice|axis) encountered')
   1260     return bypixel.pipeline(source, schema, canvas, glyph, agg, antialias=antialias)

File C:\hv116\test\.venv_wc\lib\site-packages\numpy\__init__.py:320, in __getattr__(attr)
    317     from .testing import Tester
    318     return Tester
--> 320 raise AttributeError("module {!r} has no attribute "
    321                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'warnings'

:DynamicMap   []

**Comment by ianthomas23** [comment]
This is fixed, update to datashader 0.15.0 and you will be fine.

**Comment by GeoVizNow** [comment]
Confirming it works after upgrading datashader to 0.15.0.

**Comment by ianthomas23** [comment]
Thanks @GeoVizNow
