### ISSUE TITLE
pip install bokeh==2.0.0 or pip install bokeh==2.0.1 doesn't work

### ISSUE THREAD

**Issue by MatthiVH** [holoviz/holoviews#4384]
I'm trying to install holoviews on my windows pc to work with Python 3.5.

For some reason however my holoviews install doesn't succesfully complete because it keeps saying: 

ERROR: Could not find a version that satisfies the requirement bokeh>=2.0.0.
As bokeh 2.0.0/2.0.1 is quite recent, isn't there any other bokeh version that works with holoviews and python 3.5?

**Comment by philippjfr** [comment]
Seems like a similar issue to https://github.com/holoviz/holoviews/pull/4358. The problem is that bokeh >= 2.0 is not compatible with Python<3.6. We'll try to fix the dependency specification so this issue doesn't occur but for now I can only recommend upgrading Python or explicitly pinning `bokeh<2.0` when installing HoloViews.

**Comment by MatthiVH** [comment]
Ok thanks! So what would the code look like if I don't install python 3.6 yet (not sure if all my other python-packages work with the 3.6-version) -> pip install holoviews bokeh<2.0?

**Comment by philippjfr** [comment]
Yes, I would expect that to work:

```
pip install holoviews bokeh<2.0
```

**Comment by MatthiVH** [comment]
Hmm I get the output: 'The system cannot find the file specified.'

**Comment by philippjfr** [comment]
Try:

```
pip install holoviews "bokeh<2.0"
```

**Comment by MatthiVH** [comment]
Yep, that's it, that works. Many thanks!

**Comment by scottclowe** [comment]
> Seems like a similar issue to #4358. The problem is that bokeh >= 2.0 is not compatible with Python<3.6. We'll try to fix the dependency specification so this issue doesn't occur but for now I can only recommend upgrading Python or explicitly pinning `bokeh<2.0` when installing HoloViews.

Yes, that's right, this is the symptom exhibited by the underlying problem which #4358 addresses.

**Comment by MatthiVH** [comment]
Unfortunately even though it seems to be installed correctly this way using the command prompt, my PyCharm doesn't recognize holoviews -> importerror: cannot import name 'Type'.

**Comment by philippjfr** [comment]
>importerror: cannot import name 'Type'.

That to me indicates it's still installing bokeh>=2.0 or some other dependency which requires Python>=3.6. Any idea where the error is coming from? Does:

```
import holoviews.plotting.bokeh
```

provide a more informative traceback?

**Comment by philippjfr** [comment]
My proposal here is to simply [yank](https://www.python.org/dev/peps/pep-0592/) Panel 0.9.0 - 0.9.3.

**Comment by philippjfr** [comment]
Done. Sorry for the hassle and thanks for your efforts trying to fix this @scottclowe.
